dataset: 'election'

model:
  loss: 'bernoulli_loss'
  loss_kwargs: {}
  reg: 'clip_reg'
  reg_kwargs: {lambd: [1.0e-5, 0.99999]}
  coef: {lambd_1: 0.2, lambd_2: 2.0, eta: 0.001, mu: 0.1}
  
optim:
  # alg: 'Org'
  # rel_tol: 1.0e-5
  # abs_tol: 1.0e-5
  # maxiter: 500
  # n_jobs: 2
  # verbose: False
  alg: 'MAPG'
  alpha_x: 1.0e-3
  alpha_y: 5.0e-5
  res_tol: 1.0e-4
  max_iter: 1000
  n_jobs: 1
